apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: microservices
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      serviceAccountName: user-service-sa
      containers:
        # --- Spring Boot microservice ---
        - name: payment-service
          image: us-central1-docker.pkg.dev/analog-fastness-476914-t3/microservices/payment-service:0.1.8
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "256Mi"
          #   limits:
          #     cpu: "300m"
          #     memory: "512Mi"
          envFrom:
            - configMapRef:
                name: payment-service-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials-payment
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials-payment
                  key: password
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username

            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
          readinessProbe:
            httpGet:
              path: /payment/actuator/health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /payment/actuator/health
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /payment/actuator/health
              port: 8083
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 30

        # --- Cloud SQL Proxy Sidecar ---
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.3
          args:
            - "--port=3306"
            - "analog-fastness-476914-t3:us-central1:online-ordering-mysql"
          # resources:
          #   requests:
          #     cpu: "50m"
          #     memory: "64Mi"
          #   limits:
          #     cpu: "200m"
          #     memory: "256Mi"
          volumeMounts:
            - name: cloudsql-sa-key
              mountPath: /secrets
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/key.json
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
      volumes:
        - name: cloudsql-sa-key
          secret:
            secretName: cloudsql-sa-key
