apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: microservices
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://127.0.0.1:3306/orderdb"
  PRODUCT_SERVICE_URL: "http://product-service:8081/product/api/products"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_RABBITMQ_HOST: "rabbitmq.microservices.svc.cluster.local"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_VIRTUAL_HOST: "my_vhost"
