apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: microservices
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://127.0.0.1:3306/userdb"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"